blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/web-push-libs/web-push-php/blob/master/README.md
    about: Please read the documentation before opening an issue
  - name: 💬 Discussions
    url: https://github.com/web-push-libs/web-push-php/discussions
    about: Ask questions and discuss ideas with the community
